# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('waiting_people', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.DecimalField(decimal_places=0, max_digits=2)),
                ('state', models.DecimalField(decimal_places=0, max_digits=1)),
                ('x', models.DecimalField(decimal_places=0, max_digits=5)),
                ('y', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=False)),
                ('restaurant_num', models.DecimalField(decimal_places=0, max_digits=2)),
                ('restaurant', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
                ('seat', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Seat')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='reserve',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Waiting'),
        ),
    ]
