# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reserve',
        ),
        migrations.AddField(
            model_name='user',
            name='reserve',
            field=models.ManyToManyField(default=b'', to='restaurant.Waiting'),
        ),
    ]
