# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20170624_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
