# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_globalnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_reserve',
            field=models.BooleanField(default=False),
        ),
    ]
