# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_user_if_reserve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiting',
            old_name='type',
            new_name='is_restaurant',
        ),
    ]
