# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20170624_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiting',
            old_name='restaurant_num',
            new_name='restaurant_waiting_no',
        ),
    ]
