# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_user_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='resever_valid',
            field=models.BooleanField(default=False),
        ),
    ]
