# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurant_resever_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='waiting_people',
            new_name='number_plate',
        ),
    ]
