# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20170625_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='floor',
            field=models.DecimalField(decimal_places=0, default=-3, max_digits=3),
        ),
    ]
