# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_restaurant_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_clerk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='user',
            name='rehearsal',
            field=models.ManyToManyField(null=True, related_name='rehearsal', to='restaurant.Waiting'),
        ),
        migrations.AddField(
            model_name='waiting',
            name='if_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waiting',
            name='reserve_time',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=40),
        ),
        migrations.AddField(
            model_name='waiting',
            name='reserve_time_string',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='reserve',
            field=models.ManyToManyField(null=True, related_name='reserve', to='restaurant.Waiting'),
        ),
    ]
