# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20170629_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiting',
            name='if_online_reserve',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rehearsal',
            field=models.ManyToManyField(default=b'', related_name='rehearsal', to='restaurant.Waiting'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reserve',
            field=models.ManyToManyField(default=b'', related_name='reserve', to='restaurant.Waiting'),
        ),
    ]
