# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_waiting_restaurant_reserve_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reserve',
            field=models.ManyToManyField(default=b'', to='restaurant.Waiting'),
        ),
    ]
