# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20170629_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('floor', models.DecimalField(decimal_places=0, default=-3, max_digits=3)),
                ('number_plate', models.DecimalField(decimal_places=0, max_digits=5)),
                ('current_call', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
